### ISSUE TITLE
Month jumping on date selection

### ISSUE THREAD

**Issue by teksebarna** [hypeserver/react-date-range#441] opened 2021-01-29 10:21 UTC
## Subject of the issue
I'm using _DateRangePicker_  in a Next.js project.
There are two months next to each other, let's say January and February. When I select the start date from the second month (February), then it jumps to the left, replacing the first month (January). And on the right, a new month jumps in (March).
 
## [BUG] Bug Reproduce Steps

1. Go to [this demo page](https://csb-3e52n-l3tgwabop.vercel.app/).
2. Select the start date from the second month
3. Second month jumps to the left 
You can observe this issue in [this video](https://www.screencast.com/t/beAqdTNk7).

## [BUG] Expected behavior
Same behavior as on [your demo page](https://hypeserver.github.io/react-date-range/#!/DateRangePicker/1) or [in this video](https://www.screencast.com/t/NJkEXXYz).
When selecting the start date from the second month: both months stay in place.

## Environment
Package Version: 1.1.3
React version: ^16.13.1
Next version: 10.0.6
Node version: 10.23.0
Browser: Chrome  88.0.4324.104 

Here are all dependencies from _package.json_:
"dependencies": {
    "date-fns": "2.16.1",
    "next": "latest",
    "react": "^16.13.1",
    "react-date-range": "1.1.3",
    "react-dom": "^16.13.1"
  },

Any help will be kindly appreciated.
Thank you!

**Comment by jjolmo** [comment] 2021-02-03 11:28
+1!
Totally needed this feature! Can't find a way to keep it where it is

**Comment by Skorpioh** [comment] 2021-02-03 11:48
+1 here as well; very much looking forward to having this unwanted feature/bug fixed

**Comment by Hanf92** [comment] 2021-02-23 20:26
Nothing?

**Comment by aaron5670** [comment] 2021-02-25 19:24
+1! Need this feature too... :(

**Comment by aaron5670** [comment] 2021-02-26 10:32
A better solution is maybe a small animation.
Like the example bellow. 👀 
![animation](https://user-images.githubusercontent.com/17295145/109289271-419f9580-7826-11eb-97cc-d274efbf3a48.gif)

**Comment by teksebarna** [comment] 2021-02-26 17:37
One thing I don't understand: how come it's working perfectly on their demo page: https://hypeserver.github.io/react-date-range/#!/DateRangePicker/1 ?

**Comment by isaac1104** [comment] 2021-04-21 17:18
Any updates on this issue?

**Comment by subwai** [comment] 2021-05-07 00:32
I managed to track down the issue to https://github.com/hypeserver/react-date-range/pull/399
In my opinion the logic in `calcFocusDate` is flawed from the start. It always assumes you want to focus to the `startDate` & it can't tell the difference between a click in the calendar vs an external selection like clicking a defined range.

I started writing a PR that implements the use of `focusedRange[1]` to at least prioritize `endDate` over `startDate` which will work well enough for my own issue (I built my own DateRangePicker with 2 calendar components, 1 for selecting start date & 1 for end date that operates independently but shares the range).

However, I don't believe that is enough to solve the entire issue as I think the `differenceInCalendarMonths` solution that currently exists doesn't really work at all.
```
differenceInCalendarMonths(start, end) > months
```
The difference in months will always be a negative value since start is always > end. The statement will therefor never be true & the `currentFocusedDate` will therefor never be used.
The logic that existed prior to that PR was better & even worked for my own scenario, but won't work when you want to "reset" the calendar view.

An ultimate solution would be to expose a `focusedDate` prop rather than trying to solve all scenarios perfectly internally. Or maybe you could argue that it should be possible to "reset" by using a new `key` prop on the Calendar elements for those scenarios.
Thoughts?

Fyi @teksebarna, the reason it works on the demo page is because it's using a version before that PR.

**Comment by kamyar** [comment] 2021-06-10 23:12
@subwai  thank you for the great investigation and yes, the demo was outdated and we recently automated its deployment.
`focusedDate` prop sounds good to me, additionally animations would also be great.
If you can lend a hand we would appreciate it, otherwise we can finalize a decision and I will try to take a look. :)

**Comment by kamyar** [comment] 2021-06-10 23:19
It seems there is already a PR that might address it, please let us know what your thoughts are regarding that: https://github.com/hypeserver/react-date-range/pull/428
Duplicate of #427

**Comment by owenbirdsall** [comment] 2021-06-26 10:45
Does anyone have a temporary workaround for this, or is it best to just use an older version for now?

**Comment by LucyMac** [comment] 2021-07-06 09:21
I'm also having this issue, I need the month layout to stay consistent regardless of calendar date selection.
@kamyar #428 looks good as far as I can tell - merging this would be amaaaazing 😃

**Comment by kamyar** [comment] 2021-07-06 11:53
Hey @LucyMac we already added this option, can you take a look at `retainEndDateOnFirstSelection` prop in [version 1.3.0](https://github.com/hypeserver/react-date-range/releases/tag/release%2F1.3.0)?

Would appreciate if you confirm if it works so I can close this issue

**Comment by LucyMac** [comment] 2021-07-06 12:44
Ah awesome, thanks @kamyar 😊

**Comment by Tcheetox** [comment] 2021-08-28 08:41
+1 Also interested in this. Looking forward to avoid 'month jumping' on selection.

**Comment by kamyar** [comment] 2021-08-29 00:51
Hey all, #428 is merged, will try to make a release today :)
Sorry regarding the delay 😅

**Comment by qxFisher** [comment] 2021-09-13 14:24
@kamyar Hello! 
Is it possible to completely disable month jumping (focusing on start date) in calendar?

**Comment by kamyar** [comment] 2021-09-13 23:50
@qxFisher with latest release I believe you can do it, can you check 1.4.0?
see the changelog file for the new props.

**Comment by kamyar** [comment] 2021-09-13 23:51
closing this as it was recently released with 1.4.0

**Closed by kamyar** 2021-09-13 23:51 UTC
Labels: awaiting response
